# Generated by Django 4.0.4 on 2022-05-18 22:14

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("django_pat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenDjangoPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("permission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.permission")),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="django_permissions",
                        to="django_pat.personalaccesstoken",
                    ),
                ),
            ],
        ),
    ]
