commitish: 'main'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: 'Maintenance'
    labels:
      - 'chore'
template: |
  ## Changes

  $CHANGES
